version: '3.8'

services:

  postgres-db:

    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: studentManagement
    ports:
      - "5432:5432"

  postgres-adminer:
  
    image: adminer
    restart: always
    ports:
      - "80:8080"