#NameSpace
apiVersion: v1
kind: Namespace
metadata:
  name: dev


#ConfigMap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-boot-app-curd-config
  namespace: dev
data:
  dbURL: "jdbc:postgresql://postgres-db/studentManagement"


#Secrets values are in base64
---
apiVersion: v1
kind: Secret
metadata:
  name: spring-boot-app-curd-secret
  namespace: dev
data:
  dbUserName: cG9zdGdyZXM=
  dbPassword: cG9zdGdyZXM=


#Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app-curd-deploy
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app-curd
  template:
    metadata:
      labels:
        app: spring-boot-app-curd
    spec:
      containers:
        - image: sarathvedha/spring-boot-curd-app:latest
          name: spring-boot-app-curd
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: spring-boot-app-curd-config
                  key: dbURL
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: spring-boot-app-curd-secret
                  key: dbUserName
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: spring-boot-app-curd-secret
                  key: dbPassword
          ports:
            - containerPort: 8080


#Service
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app-curd-svc
  namespace: dev
spec:
  selector:
    app: spring-boot-app-curd
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer