apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-curd-app-deploy
  labels:
    app: spring-boot-curd-app
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-curd-app
  template:
    metadata:
      name: spring-boot-curd-app
      labels:
        app: spring-boot-curd-app
    spec:
      containers:
        - name: spring-boot-curd-app
          image: sarathvedha/spring-boot-curd-app:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  key: dbURL
                  name: spring-boot-curd-app-config
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: dbUserName
                  name: spring-boot-curd-app-secret
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: dbPassword
                  name: spring-boot-curd-app-secret
          ports:
            - containerPort: 8080
      restartPolicy: Always
      